### PR TITLE
feat(stdlib): add debug.slurp and debug.sink

### PR DESCRIPTION
**Pull request by jsternberg**
This adds two new debug functions.

`debug.slurp` will read and copy multiple buffers into a single buffer.
This can be used to test the performance impact of multiple buffers or a
single buffer.

`debug.sink` is a transformation that drains all of the data from
incoming tables.

### Done checklist
- [x] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

**Review by skartikey — APPROVED** [review]
Looks good!

**Comment by nathanielc** [comment]
@jsternberg Does debug.sink meet the DOD here https://github.com/influxdata/flux/issues/3592 ? If so can you close that issue?

**Comment by jsternberg** [comment]
Oh yes. I forgot that issue existed.

**Comment by nathanielc** [comment]
Thanks! I just took a look at this PR. I don't see any acceptance tests for the new debug functions? Could you add one for debug.sink at least? I get that adding an acceptance test for debug.slurp isn't all that valuable as its an internal change not a semantic change.

**Pull request merged**
