### PR TITLE
fix(compiler): should not call CheckKind when evaluating logical expr…

### PR DESCRIPTION
**Pull request by jlapacik**
…essions

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

**Comment by nathanielc** [comment]
@jlapacik Can you make a quick audit of all CheckKinds and just remove all of them once and for if they are no longer needed?

**Comment by jlapacik** [comment]
@nathanielc they've all been removed. This was the only one left in place.

**Comment by nathanielc** [comment]
Ok a quick search showed a few commented out ones, should we remove those as well?

**Comment by jlapacik** [comment]
Sure I can uncomment them.

**Pull request merged**
