### PR TITLE
feat(contrib/zenoss): support apiKey parameter

### PR DESCRIPTION
**Pull request by sranka**
Closes influxdata/feature-requests#371

This PR enhances `contrib/bonitoo-io/zenoss` package to support also Zenoss Cloud authentication via 'z-api-key' HTTP header as described in https://docs.zenoss.io/api/zenoss-api.html

### Done checklist
- [ ] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

**Comment by ivankudibal** [comment]
@aanthony1243 pls can you help us find the right reviewer?

**Review by sanderson — APPROVED** [review]
👍🏻 Docs look good

**Comment by abalone23** [comment]
Can someone review and approve this?

**Review by Marwes — APPROVED** [review]

**Comment by Marwes** [comment]
Needs a rebase but LGTM

**Comment by sranka** [comment]
rebased, ready to merge

**Pull request merged**
