### PR TITLE
refactor: handle parsing errors with BadExpressions over panics

### PR DESCRIPTION
**Pull request by bthesorceror**

### CODE REVIEW

**Comment by bthesorceror** [comment]
@adrian-thurston I've added a test around this to illuminate where we were seeing the panic in the LSP.

**Comment by adrian-thurston** [comment]
@bthesorceror Okay thanks. At first I thought this was a regression in the rust parser because the scanner allows for a time literal with no timezone information on the end. But it looks like the go parser does the same ... allows the missing timezone in the scanner and fails during the RFC3339 parse. Perhaps it is to get more detailed error information, other than "scanner failed".

**Comment by nathanielc** [comment]
Yes, the SPEC states that we support those shorter formats https://github.com/influxdata/flux/blob/master/docs/SPEC.md#date-and-time-literals but we have not implemented them yet. See https://github.com/influxdata/flux/issues/152 although it seems that the scanner supports those formats, just not the parser.

So for now we can just improve the error message to say something like shorthand time literals are not implemented yet.

**Comment by adrian-thurston** [comment]
Ah okay, thank you for the background @nathanielc

**Pull request merged**
