### PR TITLE
docs: separate build comments and commands

### PR DESCRIPTION
**Pull request by donalod**
docs: separate build comments and commands

### Done checklist. checklist NA as docs only
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

**Review by Marwes — APPROVED** [review]

**Comment by donalod** [comment]
@Marwes did this get stuck? The conventional commit message should not invoke a full test run?

**Comment by Marwes** [comment]
No job seems to exist in circleCI, you could try to rebase and force push to trigger a new run.

**Comment by donalod** [comment]
@Marwes this is my second attempt (https://github.com/influxdata/flux/pull/4872) to raise a trivial PR for flux/Influx. We had to delete the previous one. I am using the Github UI during my brief breaks in my working day. I am not a paid Influx employee and was trying to clarify the flux install documentation with some newlines as I lost hours trying to install the REPL recently and had also stolen time from people in the Influx Slack https://influxcommunity.slack.com/archives/CH8RGRW4T/p1654778081540739 . I reformatted the new PR with conventional commits as requested. I'm afraid I don't have time for this, am not privy to the Influx internals/CI and would request someone reruns the actions or takes responsibility for fixing the doco :(  Maybe @wolffcm could...

**Comment by wolffcm** [comment]
In the last PR, there was a button I could click (as an org member) to trigger the job running in CI. We don't have logic to turn off CI for simple things like doc changes, since they are pretty infrequent.

Not sure what's going on here. I'll open a new PR with that cherry-picks this commit and see if that triggers it.

**Comment by wolffcm** [comment]
I filed this PR, which does have CI running as it should https://github.com/influxdata/flux/pull/4888

**Comment by wolffcm** [comment]
This is now merged in #4888, thanks @donalod for taking the initiative to fix this, it will certainly help folks out as you've noted.

**Comment by Marwes** [comment]
@donalod Sorry about that, normally I would have triggered a manual re-run but since no run showed I didn't have a way to do that :( . Seems likely that there is some issue between circleci and needing one of us maintainers to approve CI explicitly.

**Pull request closed without merging**
