### PR TITLE
chore(stdlib): Move boundaries package to experimental

### PR DESCRIPTION
**Pull request by scbrickley**
Related to #5030 

This will break user queries, but the boundaries package is relatively young, so it may not be that much of a problem. I'll look through the query archiver to assess the blast radius before merging.

### CODE REVIEW

**Review by wolffcm — APPROVED** [review]
This looks good.

I know we can test for error messages in acceptance tests now... might be worth trying that out for this? I'll leave it up to you.

**Comment by hellow554** [comment]
As already suggested in #5019 I would like to see, that `boundaries/week` returns the current week, if the current day is the start day of the week. Maybe it can be done in this PR?

**Review by wolffcm — APPROVED** [review]
This still looks good to me.

**Comment by wolffcm** [comment]
@sanderson This seems like a PR that you should be aware of. For context, the `boundaries` package landed outside of `experimental/` a few weeks ago, but consensus is that we'd like to continue to iterate on it, so we're moving it back there, pending understanding of how widely it's used now.

**Review by wolffcm — APPROVED** [review]

**Pull request merged**
