### PR TITLE
feat(stdlib/contrib): add sensu package

### PR DESCRIPTION
**Pull request by sranka**
This PR adds contrib/sranka/sensu package to flux so that events can be sent from flux to Sensu.

Notes:
- the implementation and tests follow the concepts in existing "slack", "contrib/sranka/telegram" and "contrib/sranka/teams" package
- flux's sensu package will be then used in influxdata/influxdb to introduce a new sensu notification endpoint/rule type
- sensu package has its own README.md 

### Done checklist
- [ ] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

**Comment by nathanielc** [comment]
@sranka Thanks! I have pinged someone on the team to take a look

**Comment by sranka** [comment]
There are now the following failing tests after my changes. 
```
---- tests::find_var_ref_obj_with stdout ----
thread 'tests::find_var_ref_obj_with' panicked at 'assertion failed: `(left == right)`
  left: `"{int:int | ethan:t5062 | t5066}"`,
 right: `"{int:int | ethan:t4951 | t4955}"`', src/flux/lib.rs:687:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::find_var_ref stdout ----
thread 'tests::find_var_ref' panicked at 'assertion failed: `(left == right)`
  left: `"{int:int | sweet:t5066 | str:string | t5077}"`,
 right: `"{int:int | sweet:t4955 | str:string | t4966}"`', src/flux/lib.rs:622:9

---- tests::find_var_ref_query stdout ----
thread 'tests::find_var_ref_query' panicked at 'assertion failed: `(left == right)`
  left: `"{measurement:t5071 | timeRangeStart:t5081 | timeRangeStop:t5083 | bucket:string | t5119}"`,
 right: `"{measurement:t4960 | timeRangeStart:t4970 | timeRangeStop:t4972 | bucket:string | t5008}"`', src/flux/lib.rs:730:9
```
These tests are quite new (1 day old), they compare generates types, which fails. Introduced by https://github.com/influxdata/flux/commit/513503070bd3ad3f2cbb3fb6811222236d2ef59b 

@yzhang1991 can you please repair these tests (regexp to replace generated types before comparison?)

**Comment by sranka** [comment]
@yzhang1991 @nathanielc - #3002 repairs the tests, it shall be merged before this PR

**Comment by yzhang1991** [comment]
Hi @sranka, can you please rebase your branch to catch up with the latest master of flux?
I landed https://github.com/influxdata/flux/pull/3009 today to fix the test issue you encountered, it should be OK now.

**Comment by sranka** [comment]
Rebased, thank you @yzhang1991 for the type normalizer.

**Review by yzhang1991 — APPROVED** [review]

**Pull request merged**
