### PR TITLE
feat: mqtt to() function

### PR DESCRIPTION
**Pull request by davidgs**
### Done checklist
- [ X] docs/SPEC.md updated
- [ X] Test cases written

### CODE REVIEW

**Comment by onyxet** [comment]
Hi guys! Thanks for this great feature!
Any updates when it could be merged?

**Comment by davidgs** [comment]
It's actually been merged a while ago, but it is in the `experimental` pkg, so all you need to do in a flux task is:

`import` experimental/mqtt
|> mqtt.to(
		broker: "tcp://yourbroker.com:port,
		topic: "topicname",
		clientid: "optional-client-id",
		valueColumns: ["_value"],
		tagColumns: ["cpu", "host"],
	)`
And you should be good to go!

**Comment by onyxet** [comment]
@davidgs And we have to use InfluxDB v2 as I understood ?

**Comment by davidgs** [comment]
I believe so, as there are no tasks in InfluxDB v1 -- I think it's still in the version of flux shipped with 1.8 so in theory you could I guess.

**Comment by onyxet** [comment]
@davidgs Thank you for support

**Comment by mike006322** [comment]
Could there be an option for the MQTT message to be in JSON format instead of line protocol?

**Comment by davidgs** [comment]
You're welcomed to implement such a feature.

**Pull request closed without merging**
