### PR TITLE
feat(cmd): add trace option to the flux cli

### PR DESCRIPTION
**Pull request by jsternberg**
### Done checklist
- [x] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

**Review by nathanielc — COMMENTED** [review]
How do you use this? Looks like you need your local env to be configured to point to a jaeger install? Is the intent that it would be an existing production install? Or one inside the isolation testing env? 

Does adding a trace client side associate the trace with the server side trace/spans?

**Comment by jsternberg** [comment]
It's mostly meant to be used with a local jaeger. You run the jaeger docker image and then just use `--trace` and it will upload it to your local one on localhost. Since this is the CLI, there are no server side trace/spans. It's just taking the existing opentracing infrastructure and allowing it to be used from the CLI.

It was originally removed when we removed the opentracing components. Then @wolffcm added better designed ones in and this became useful again.

**Comment by wolffcm** [comment]
Can we include quick instructions (or a link) somewhere on how to set up a local Jaeger? I can see this being useful.

**Comment by onelson** [comment]
https://www.jaegertracing.io/docs/1.33/getting-started/#all-in-one

**Review by nathanielc — APPROVED** [review]

**Pull request merged**
