### PR TITLE
chore: fix cumulative sum integration tests

### PR DESCRIPTION
**Pull request by jsternberg**
### Checklist

Dear Author :wave:, the following checks should be completed (or explicitly dismissed) before merging.

- [x] ✏️ Write a PR description, regardless of triviality, to include the _value_ of this PR
- [x] 🔗 Reference related issues
- [x] 🏃 Test cases are included to exercise the new code
- [x] 🧪 If **new packages** are being introduced to stdlib, link to Working Group discussion notes and ensure it lands under `experimental/`
- [x] 📖 If **language features** are changing, ensure `docs/Spec.md` has been updated

Dear Reviewer(s) :wave:, you are responsible (among others) for ensuring the completeness and quality of the above before approval.

### CODE REVIEW

**Review by scbrickley — COMMENTED** [review]
To clarify, the fix here was just removing `testing.load()` and moving the declarations of `inData` and `outData` to be within each testcase?

**Comment by jsternberg** [comment]
The fix was just to remove `testing.load()` by itself. I just also consolidated the test cases to one file.

**Review by scbrickley — APPROVED** [review]

**Comment by scbrickley** [comment]
Do we know why `testing.load()` causes these tests to fail?

**Comment by jsternberg** [comment]
Yea. For two of them, they wrote duplicate data that isn't compatible with influxdb's data model. For one of them, they didn't have a value column so couldn't be written.

**Pull request merged**
