### PR TITLE
fix(execute): metadata in flux statistics needs to be initialized

### PR DESCRIPTION
**Pull request by jsternberg**
### Done checklist
- [x] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

**Review by onelson — APPROVED** [review]
Sure. Is this what blew up in the nightly job?

**Comment by jsternberg** [comment]
I didn't know the nightly job blew up. Quite probably since it blew up in a PR I was attempting to make.

**Comment by onelson** [comment]
Yeah, nightly was full of `panic: assignment to entry in nil map` last night.

```
	range_nsecs_group_last...fail: panic: assignment to entry in nil map
	range_nsecs_window_sum...fail: panic: assignment to entry in nil map
	range_nsecs_window_first...fail: panic: assignment to entry in nil map
	range_nsecs_window_min...fail: panic: assignment to entry in nil map
	range_nsecs_agg_count...fail: panic: assignment to entry in nil map
	range_nsecs_agg_last...fail: panic: assignment to entry in nil map
	window_period_gaps...fail: panic: assignment to entry in nil map
	window_offset...fail: panic: assignment to entry in nil map
	window_negative_offset...fail: panic: assignment to entry in nil map

---
Found 348 tests: passed 170, failed 141, skipped 37
panic: assignment to entry in nil map
exit status 1
```

**Comment by jsternberg** [comment]
Yep that's it.

**Pull request merged**
