### PR TITLE
fix(stdlib): sort statuses also by _time

### PR DESCRIPTION
**Pull request by alespour**
This PR fixes issue in alerting where, depending on check and rule scheduling and timing configuration, state changes are sometimes not detected and therefore notifications not sent.

The problem is that status of data points may be evaluated multiple times with certain scheduling, for example as reported in #3807, deadman check evaluates status based on data point time and not a metric value. That results in existence of multiple statuses with the same source timestamp but different time (and level) in the monitoring bucket. Then, when an alert rule attempts to detect state change, it gets incorrect sequence of statuses, because sorting by only (the same) source timestamp is insufficient.

Affected functions are `stateChangesOnly` and `_stateChanges` functions in `monitor` package, where before `sort`,
`_level` is dropped from the group key which results in a new series with possibly unpredictable order (by `_time`).

The issue is a side effect of the changes in #2725. Mea culpa.

### Done checklist
- [x] Test cases written

### CODE REVIEW

**Review by wolffcm — CHANGES_REQUESTED** [review]
The fix looks good and the changes make sense. Thanks for fixing this!

Can I trouble you to adapt your test to our newer format which uses a Flux keyword `testcase`? We want to be using it moving forward. Here is an example:
https://github.com/influxdata/flux/blob/955bc0303789cce8938d69b55c7e1697962f1d7e/stdlib/universe/window_test.flux#L7

**Comment by alespour** [comment]
@wolffcm Done. Nice feature!

**Review by wolffcm — APPROVED** [review]
Look great. Thanks again!

**Comment by jsternberg** [comment]
Fixed using @wolffcm's first suggestion in https://github.com/influxdata/flux/pull/4012.

**Pull request merged**
