### PR TITLE
feat: add influxdata semantic commit and PR title validator.

### PR DESCRIPTION
**Pull request by tysonkamp**
### Done checklist
- [N/A ] docs/SPEC.md updated
- [ N/A] Test cases written

When this is approved, merged and I've validated it's working correctly, I will remove semantic-pull-requests from this repo.

### CODE REVIEW

**Review by onelson — COMMENTED** [review]
> When this is approved, merged and I've validated it's working correctly, I will remove semantic-pull-requests from this repo.

I'm catching up here -- is this to say the existing check (assumed happening via CircleCI) will be removed in favor of this GitHub Action?

**Comment by onelson** [comment]
lol - I'm looking at old PRs to see where the semantic PR validation _used to happen_ (I swear we had this before!) but I don't actually see it?! I've lost my marbles apparently. What happened here...

**Review by onelson — APPROVED** [review]

**Comment by tysonkamp** [comment]
Hi @onelson , yes that check for semantic-pull-requests should appear here and I don't know why it doesn't. I'm going to do another check in to see the new semantic checker run as a GH action prior to pushing it forward.  When that happens, can I "squash and merge", or is there a process for getting PRs merged into main/master?

**Comment by onelson** [comment]
You're fine. "Squash and merge" at your convenience when approved.

**Comment by onelson** [comment]
iirc, GH Actions will only look at the workflow configs in the default branch, so I'm not surprised this check isn't firing yet. I could be wrong.

I just expected old PRs to still show the old checks (and I don't see them).

**Comment by tysonkamp** [comment]
Discussed with team, merging.

**Pull request merged**
