### PR TITLE
chore: update PolyType and MonoType String() method to be deterministic

### PR DESCRIPTION
**Pull request by wolffcm**
This PR concerns the new `PolyType` and `MonoType` structs that are backed by flat buffers.

This change updates the `String()` method for `PolyType` and `MonoType` to make them more useful, so that output is always consistent. This will make them easier to use in tests.

### CODE REVIEW

**Comment by wolffcm** [comment]
Yes, you're right, I'll sort those too.  

I opted not to sort row fields, since they are implemented as a linked list in Rust for `PolyType`, do you think there's any chance their order could vary as well?

**Comment by jlapacik** [comment]
@wolffcm that's a good point. Property order can vary except for the relative order of properties with the same key. I.e if `k: "a", v: int` comes before `k: "a", v: float` in one ordering, it must be like that for every ordering.

**Comment by jsternberg** [comment]
It doesn't look like the MonoType `String()` has been updated to be sorted in this PR. I didn't see any changes to that `String()` function.

**Comment by wolffcm** [comment]
@jsternberg Function arguments are now sorted in the `MonoType` `String()` method, maybe you missed it.  I still need to do constraints on polytypes and fields in Rows.

**Pull request merged**
