### PR TITLE
ci: rust checkfmt

### PR DESCRIPTION
**Pull request by yzhang1991**
### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

**Comment by jlapacik** [comment]
Just to echo what @affo said, I would prefer to ignore generated files, but approving anyway.

**Comment by yzhang1991** [comment]
I tried the ignore option, got this:
```
Warning: can't set `ignore = IgnoreList { path_set: {"src/ast/flatbuffers/ast_generated.rs", "src/ast/flatbuffers/semantic_generated.rs"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/ast/flatbuffers/semantic_generated.rs", "src/ast/flatbuffers/ast_generated.rs"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/ast/flatbuffers/semantic_generated.rs", "src/ast/flatbuffers/ast_generated.rs"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
```

Rebased the PR against master

**Comment by yzhang1991** [comment]
In this case, I feel formatting the generated code is OK. Unless you have some strong reasons not to @jlapacik @affo .

**Comment by affo** [comment]
@yzhang1991 Oh, only available in nightly.

Go ahead then 👍 

Thank you!

**Pull request merged**
