### PR TITLE
Added fluxcli binary cmd

### PR DESCRIPTION
**Pull request by aanthony1243**

### CODE REVIEW

**Comment by goller** [comment]
@aanthony1243 this is very similar to my work in platform.  Could this be moved there?

**Comment by stuartcarnie** [comment]
@goller the expectation is that flux has an independent, standalone binary, with support for CSV and other contributed sources, directly from this repository to be readily go installable

**Comment by goller** [comment]
Gotcha.

Is there any need to keep the API for platform and fluxcli in-sync?  Perhaps fluxcli API lives its own life?

**Comment by aanthony1243** [comment]
I think it's just supposed to be a source-agnostic client that can get users started with flux.  The fact that it's chronograf-compatible was just a quick feature we built-in for a compelling demo on the hack day.  I think we can maintain this independently of the product API

**Pull request merged**
