### PR TITLE
feat: getters for a window's every and period

### PR DESCRIPTION
**Pull request by jlapacik**
### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

**Comment by nathanielc** [comment]
Can you explain the reasoning behind exposing the `every` and `period`? The reason they were not exposed initially is so that consumers of the interval code could not do their own duration math, instead they are required to use the provided Bounds API.

**Comment by jlapacik** [comment]
When pushing bare aggregates down to storage, the query planner sets the `every` parameter to the max value. Storage then checks this value to determine which implementation to use (bare vs window).

**Review by rockstar — APPROVED** [review]
This code itself looks fine, but I'm interested in the conversation between you and @nathanielc at an architectural level; I can't confidently comment on that.

**Review by nathanielc — APPROVED** [review]
Thanks for the clarification. Can you make sure to change the PR title so that the message that makes it into the change log and git logs is accurate?

**Pull request merged**
